### ISSUE TITLE
Flatmap default view, zoom in and zoom out behaviour, tooltip.

### ISSUE THREAD

**Issue by dbrnz** [dbrnz/flatmap-mvt-viewer#13]
What about popup modal on flatmap?

Ex Asana [task](https://app.asana.com/0/563768015703431/1171525850355294) -- see [this document](https://drive.google.com/file/d/1ZWuE9mQJdFwvFFIz3Gfzi_YP7qeLVte3/view?ts=5e97b53f) for details.

- [x] #14 -- change location and style of zoom control.
- [x] #15 -- change initial view of flatmaps.
- [x] #16 -- change font and background of labels.

**Comment by uxdesigndept** [comment]
username: uxdesigndept

**Comment by dbrnz** [comment]
@uxdesigndept and @alan-wu, these changes are in release `0.9.5` of `@dbrnz/flatmap-viewer`. Please see the individual issues for details.

**Comment by alan-wu** [comment]
Thanks.

**Comment by dbrnz** [comment]
Closed with release 0.9.6 of `@dbrnz/flatmap-viewer`.
